name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Mnaual Trigger"
        default: "MT"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: py.test --cov --cov-report=xml owm tests -vv
      - name: sonar-scanner
        uses: Warchant/setup-sonar-scanner@v4
      - run: sonar-scanner
           -Dsonar.organization=jgennari 
           -Dsonar.projectKey=jgennari-2023-devsecops-example 
           -Dsonar.sources=owm/
           -Dsonar.tests=tests/
           -Dsonar.verbose=true
      - run: coveralls
